version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanagerdb  # Nombre de la base de datos que quieres crear
    ports:
      - "3306:3306"  # Exponer el puerto para acceder desde el Codespace
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
